name: Approve and Merge
on:
  pull_request:
  workflow_dispatch:

jobs:
  approve-and-merge:
    name: Publish and Merge
    runs-on: ubuntu-latest
#    permissions:
#      pull-requests: write
#    if: github.actor == 'github-actions'
    steps:
      - name: Auto Approve PR
        uses: hmarr/auto-approve-action@v4
      - name: Push next version release
        uses: pascalgn/automerge-action@v0.16.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "Bump Version"
